### PR TITLE
Add wysiwyg support

### PR DESCRIPTION
**Pull request by JasonHoffmann**
Ok, this adds WYSIWYG support in a basic way.

It uses the global defaults of the content field to initiate tinyMCE instead of a custom setup, but it gets us a good amount of the way there.

In order for it to work generally, each group that's created is given a separate name, then a hidden field is added to capture that name and piece it all together during sanitization.

Also cleans up some styles.

### CODE REVIEW

**Comment by jtsternberg** [comment]
Just a comment, as I know this sortof the v1 or whatever, but not all post-types will have the content field as a registered support, so in those cases, you wouldn't have the global default available.

**Comment by JasonHoffmann** [comment]
Yea it will definitely need to be amended before this is even truly beta. I want to step through and pull it from the WP hook dynamically, but this was a good first step.

**Comment by JasonHoffmann** [comment]
@jjeaton never pushed it to staging. It's up in the image group now.

**Comment by jjeaton** [comment]
I wasn't able to reproduce the "error while saving" issue locally. I'm going to merge this, and we can come back to fix anything later.

**Pull request merged**
